env: standard
runtime: nodejs16
service: default

handlers:
  - url: /.*
    secure: always
    script: auto
instance_class: F1
automatic_scaling:
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 30ms
